GET http://localhost:5000/

###

POST http://localhost:5000/acara/baru
Content-Type: application/json

{
    "namaPria":"Farhan Yakub Bawazier",
    "namaWanita":"Ida",
    "latitude":"0-01-021-0121",
    "longitude": "0-01-021-1223",
    "dresscode": "gray",
    "waktuAcara": "10020303010"
}

###

POST http://localhost:5000/acara/-MX-ypFdNBOA95Jr2ETo/invitee/baru
Content-Type: application/json

{
    "invitees":[
        {
            "namaLengkap": "Hanim Pranata",
            "email":"hanimpranata@gmail.com"
        },
                {
            "namaLengkap": "Ita Windriarti P",
            "email":"itawindriartip@gmail.com"
        }
    ]
}