GET http://localhost:5000/

###

GET http://localhost:5000/acara
Content-Type: application/json
id-token: eyJhbGciOiJSUzI1NiIsImtpZCI6IjhkOGM3OTdlMDQ5YWFkZWViOWM5M2RiZGU3ZDAwMzJmNjk3NjYwYmQiLCJ0eXAiOiJKV1QifQ.eyJuYW1lIjoiYWRpIiwiaXNzIjoiaHR0cHM6Ly9zZWN1cmV0b2tlbi5nb29nbGUuY29tL2FuZ3VsYXItOTYyOTkiLCJhdWQiOiJhbmd1bGFyLTk2Mjk5IiwiYXV0aF90aW1lIjoxNjE3NTI0NzQwLCJ1c2VyX2lkIjoiRTJWN014NXBqMVRhMXFxSXhnUmdSbXZUUmdnMSIsInN1YiI6IkUyVjdNeDVwajFUYTFxcUl4Z1JnUm12VFJnZzEiLCJpYXQiOjE2MTc1MjQ3NDksImV4cCI6MTYxNzUyODM0OSwiZW1haWwiOiJyaXN0aXJpYW50b2FkaUBnbWFpbC5jb20iLCJlbWFpbF92ZXJpZmllZCI6ZmFsc2UsImZpcmViYXNlIjp7ImlkZW50aXRpZXMiOnsiZW1haWwiOlsicmlzdGlyaWFudG9hZGlAZ21haWwuY29tIl19LCJzaWduX2luX3Byb3ZpZGVyIjoicGFzc3dvcmQifX0.cXRlxdyDlotHbWETa-mmZlwgtTo8ayXlsm9qdDiDhTfr8PslhPrMWjpbukv72rGs17STOu2Virvsj_01fXFD0lz8WgbjeHXT8YZ-gavESD6LMDQ47A_l_8EdRRCVp1-R9Q1QW4z8XSNsUNEVFWtMF9kdh3wNHqyWFj2pcWAAJOib8cuJx1xDuwra89Cip6LJaVLSToyzXx4lIZvjrG8K0Rq2RdK1MV9BesmiEg8Kjf8kB5WGRk29EOFrFS1yzeAJFdAYWMY3RvnTlwELyh54ovgYV1d_7lOolmnzGeJC6Ju295Rj_6s_kMCF8wbPogoMoe6hUqr1yZBoYLlYuuKKOw


###

GET http://localhost:5000/acara/-MXKMYShnI-_zRNXhqOx
Content-Type: application/json
id-token: eyJhbGciOiJSUzI1NiIsImtpZCI6IjhkOGM3OTdlMDQ5YWFkZWViOWM5M2RiZGU3ZDAwMzJmNjk3NjYwYmQiLCJ0eXAiOiJKV1QifQ.eyJuYW1lIjoiYWRpIiwiaXNzIjoiaHR0cHM6Ly9zZWN1cmV0b2tlbi5nb29nbGUuY29tL2FuZ3VsYXItOTYyOTkiLCJhdWQiOiJhbmd1bGFyLTk2Mjk5IiwiYXV0aF90aW1lIjoxNjE3NTI0NzQwLCJ1c2VyX2lkIjoiRTJWN014NXBqMVRhMXFxSXhnUmdSbXZUUmdnMSIsInN1YiI6IkUyVjdNeDVwajFUYTFxcUl4Z1JnUm12VFJnZzEiLCJpYXQiOjE2MTc1MjQ3NDksImV4cCI6MTYxNzUyODM0OSwiZW1haWwiOiJyaXN0aXJpYW50b2FkaUBnbWFpbC5jb20iLCJlbWFpbF92ZXJpZmllZCI6ZmFsc2UsImZpcmViYXNlIjp7ImlkZW50aXRpZXMiOnsiZW1haWwiOlsicmlzdGlyaWFudG9hZGlAZ21haWwuY29tIl19LCJzaWduX2luX3Byb3ZpZGVyIjoicGFzc3dvcmQifX0.cXRlxdyDlotHbWETa-mmZlwgtTo8ayXlsm9qdDiDhTfr8PslhPrMWjpbukv72rGs17STOu2Virvsj_01fXFD0lz8WgbjeHXT8YZ-gavESD6LMDQ47A_l_8EdRRCVp1-R9Q1QW4z8XSNsUNEVFWtMF9kdh3wNHqyWFj2pcWAAJOib8cuJx1xDuwra89Cip6LJaVLSToyzXx4lIZvjrG8K0Rq2RdK1MV9BesmiEg8Kjf8kB5WGRk29EOFrFS1yzeAJFdAYWMY3RvnTlwELyh54ovgYV1d_7lOolmnzGeJC6Ju295Rj_6s_kMCF8wbPogoMoe6hUqr1yZBoYLlYuuKKOw

###

POST http://localhost:5000/acara/baru
Content-Type: application/json
id-token: eyJhbGciOiJSUzI1NiIsImtpZCI6IjhkOGM3OTdlMDQ5YWFkZWViOWM5M2RiZGU3ZDAwMzJmNjk3NjYwYmQiLCJ0eXAiOiJKV1QifQ.eyJuYW1lIjoiYWRpIiwiaXNzIjoiaHR0cHM6Ly9zZWN1cmV0b2tlbi5nb29nbGUuY29tL2FuZ3VsYXItOTYyOTkiLCJhdWQiOiJhbmd1bGFyLTk2Mjk5IiwiYXV0aF90aW1lIjoxNjE3NTI0NzQwLCJ1c2VyX2lkIjoiRTJWN014NXBqMVRhMXFxSXhnUmdSbXZUUmdnMSIsInN1YiI6IkUyVjdNeDVwajFUYTFxcUl4Z1JnUm12VFJnZzEiLCJpYXQiOjE2MTc1MjQ3NDksImV4cCI6MTYxNzUyODM0OSwiZW1haWwiOiJyaXN0aXJpYW50b2FkaUBnbWFpbC5jb20iLCJlbWFpbF92ZXJpZmllZCI6ZmFsc2UsImZpcmViYXNlIjp7ImlkZW50aXRpZXMiOnsiZW1haWwiOlsicmlzdGlyaWFudG9hZGlAZ21haWwuY29tIl19LCJzaWduX2luX3Byb3ZpZGVyIjoicGFzc3dvcmQifX0.cXRlxdyDlotHbWETa-mmZlwgtTo8ayXlsm9qdDiDhTfr8PslhPrMWjpbukv72rGs17STOu2Virvsj_01fXFD0lz8WgbjeHXT8YZ-gavESD6LMDQ47A_l_8EdRRCVp1-R9Q1QW4z8XSNsUNEVFWtMF9kdh3wNHqyWFj2pcWAAJOib8cuJx1xDuwra89Cip6LJaVLSToyzXx4lIZvjrG8K0Rq2RdK1MV9BesmiEg8Kjf8kB5WGRk29EOFrFS1yzeAJFdAYWMY3RvnTlwELyh54ovgYV1d_7lOolmnzGeJC6Ju295Rj_6s_kMCF8wbPogoMoe6hUqr1yZBoYLlYuuKKOw

{
    "namaPria":"Bayu Bagaskara",
    "namaWanita":"Lulu Lilaka",
    "latitude":"0-01-021-0121",
    "longitude": "0-01-021-1223",
    "dresscode": "sunny",
    "waktuAcara": "10020303010"
}

###

POST http://localhost:5000/acara/-MXKMYShnI-_zRNXhqOx/gallery/add
Content-Type: application/json
id-token: eyJhbGciOiJSUzI1NiIsImtpZCI6IjhkOGM3OTdlMDQ5YWFkZWViOWM5M2RiZGU3ZDAwMzJmNjk3NjYwYmQiLCJ0eXAiOiJKV1QifQ.eyJuYW1lIjoiYWRpIiwiaXNzIjoiaHR0cHM6Ly9zZWN1cmV0b2tlbi5nb29nbGUuY29tL2FuZ3VsYXItOTYyOTkiLCJhdWQiOiJhbmd1bGFyLTk2Mjk5IiwiYXV0aF90aW1lIjoxNjE3NTI0NzQwLCJ1c2VyX2lkIjoiRTJWN014NXBqMVRhMXFxSXhnUmdSbXZUUmdnMSIsInN1YiI6IkUyVjdNeDVwajFUYTFxcUl4Z1JnUm12VFJnZzEiLCJpYXQiOjE2MTc1MjQ3NDksImV4cCI6MTYxNzUyODM0OSwiZW1haWwiOiJyaXN0aXJpYW50b2FkaUBnbWFpbC5jb20iLCJlbWFpbF92ZXJpZmllZCI6ZmFsc2UsImZpcmViYXNlIjp7ImlkZW50aXRpZXMiOnsiZW1haWwiOlsicmlzdGlyaWFudG9hZGlAZ21haWwuY29tIl19LCJzaWduX2luX3Byb3ZpZGVyIjoicGFzc3dvcmQifX0.cXRlxdyDlotHbWETa-mmZlwgtTo8ayXlsm9qdDiDhTfr8PslhPrMWjpbukv72rGs17STOu2Virvsj_01fXFD0lz8WgbjeHXT8YZ-gavESD6LMDQ47A_l_8EdRRCVp1-R9Q1QW4z8XSNsUNEVFWtMF9kdh3wNHqyWFj2pcWAAJOib8cuJx1xDuwra89Cip6LJaVLSToyzXx4lIZvjrG8K0Rq2RdK1MV9BesmiEg8Kjf8kB5WGRk29EOFrFS1yzeAJFdAYWMY3RvnTlwELyh54ovgYV1d_7lOolmnzGeJC6Ju295Rj_6s_kMCF8wbPogoMoe6hUqr1yZBoYLlYuuKKOw

{
    "namaPria":"Bayu Bagaskara",
    "namaWanita":"Lulu Lilaka",
    "latitude":"0-01-021-0121",
    "longitude": "0-01-021-1223",
    "dresscode": "sunny",
    "waktuAcara": "10020303010"
}

###

GET http://localhost:5000/acara/-MXKMYShnI-_zRNXhqOx/gallery/add
Content-Type: application/json
id-token: eyJhbGciOiJSUzI1NiIsImtpZCI6IjhkOGM3OTdlMDQ5YWFkZWViOWM5M2RiZGU3ZDAwMzJmNjk3NjYwYmQiLCJ0eXAiOiJKV1QifQ.eyJuYW1lIjoiYWRpIiwiaXNzIjoiaHR0cHM6Ly9zZWN1cmV0b2tlbi5nb29nbGUuY29tL2FuZ3VsYXItOTYyOTkiLCJhdWQiOiJhbmd1bGFyLTk2Mjk5IiwiYXV0aF90aW1lIjoxNjE3NTI0NzQwLCJ1c2VyX2lkIjoiRTJWN014NXBqMVRhMXFxSXhnUmdSbXZUUmdnMSIsInN1YiI6IkUyVjdNeDVwajFUYTFxcUl4Z1JnUm12VFJnZzEiLCJpYXQiOjE2MTc1MjQ3NDksImV4cCI6MTYxNzUyODM0OSwiZW1haWwiOiJyaXN0aXJpYW50b2FkaUBnbWFpbC5jb20iLCJlbWFpbF92ZXJpZmllZCI6ZmFsc2UsImZpcmViYXNlIjp7ImlkZW50aXRpZXMiOnsiZW1haWwiOlsicmlzdGlyaWFudG9hZGlAZ21haWwuY29tIl19LCJzaWduX2luX3Byb3ZpZGVyIjoicGFzc3dvcmQifX0.cXRlxdyDlotHbWETa-mmZlwgtTo8ayXlsm9qdDiDhTfr8PslhPrMWjpbukv72rGs17STOu2Virvsj_01fXFD0lz8WgbjeHXT8YZ-gavESD6LMDQ47A_l_8EdRRCVp1-R9Q1QW4z8XSNsUNEVFWtMF9kdh3wNHqyWFj2pcWAAJOib8cuJx1xDuwra89Cip6LJaVLSToyzXx4lIZvjrG8K0Rq2RdK1MV9BesmiEg8Kjf8kB5WGRk29EOFrFS1yzeAJFdAYWMY3RvnTlwELyh54ovgYV1d_7lOolmnzGeJC6Ju295Rj_6s_kMCF8wbPogoMoe6hUqr1yZBoYLlYuuKKOw


###

POST http://localhost:5000/acara/-MX-z-kzwafxyFrasQcl/gallery/-MYi1_YgnMcXmQnF1zPe/delete
Content-Type: application/json
id-token: eyJhbGciOiJSUzI1NiIsImtpZCI6IjhkOGM3OTdlMDQ5YWFkZWViOWM5M2RiZGU3ZDAwMzJmNjk3NjYwYmQiLCJ0eXAiOiJKV1QifQ.eyJuYW1lIjoiYWRpIiwiaXNzIjoiaHR0cHM6Ly9zZWN1cmV0b2tlbi5nb29nbGUuY29tL2FuZ3VsYXItOTYyOTkiLCJhdWQiOiJhbmd1bGFyLTk2Mjk5IiwiYXV0aF90aW1lIjoxNjE3NTI0NzQwLCJ1c2VyX2lkIjoiRTJWN014NXBqMVRhMXFxSXhnUmdSbXZUUmdnMSIsInN1YiI6IkUyVjdNeDVwajFUYTFxcUl4Z1JnUm12VFJnZzEiLCJpYXQiOjE2MTc1MjQ3NDksImV4cCI6MTYxNzUyODM0OSwiZW1haWwiOiJyaXN0aXJpYW50b2FkaUBnbWFpbC5jb20iLCJlbWFpbF92ZXJpZmllZCI6ZmFsc2UsImZpcmViYXNlIjp7ImlkZW50aXRpZXMiOnsiZW1haWwiOlsicmlzdGlyaWFudG9hZGlAZ21haWwuY29tIl19LCJzaWduX2luX3Byb3ZpZGVyIjoicGFzc3dvcmQifX0.cXRlxdyDlotHbWETa-mmZlwgtTo8ayXlsm9qdDiDhTfr8PslhPrMWjpbukv72rGs17STOu2Virvsj_01fXFD0lz8WgbjeHXT8YZ-gavESD6LMDQ47A_l_8EdRRCVp1-R9Q1QW4z8XSNsUNEVFWtMF9kdh3wNHqyWFj2pcWAAJOib8cuJx1xDuwra89Cip6LJaVLSToyzXx4lIZvjrG8K0Rq2RdK1MV9BesmiEg8Kjf8kB5WGRk29EOFrFS1yzeAJFdAYWMY3RvnTlwELyh54ovgYV1d_7lOolmnzGeJC6Ju295Rj_6s_kMCF8wbPogoMoe6hUqr1yZBoYLlYuuKKOw


###

POST http://localhost:5000/acara/-MX-ypFdNBOA95Jr2ETo/edit
Content-Type: application/json
id-token: eyJhbGciOiJSUzI1NiIsImtpZCI6IjhkOGM3OTdlMDQ5YWFkZWViOWM5M2RiZGU3ZDAwMzJmNjk3NjYwYmQiLCJ0eXAiOiJKV1QifQ.eyJuYW1lIjoiYWRpIiwiaXNzIjoiaHR0cHM6Ly9zZWN1cmV0b2tlbi5nb29nbGUuY29tL2FuZ3VsYXItOTYyOTkiLCJhdWQiOiJhbmd1bGFyLTk2Mjk5IiwiYXV0aF90aW1lIjoxNjE3NTI0NzQwLCJ1c2VyX2lkIjoiRTJWN014NXBqMVRhMXFxSXhnUmdSbXZUUmdnMSIsInN1YiI6IkUyVjdNeDVwajFUYTFxcUl4Z1JnUm12VFJnZzEiLCJpYXQiOjE2MTc1MjQ3NDksImV4cCI6MTYxNzUyODM0OSwiZW1haWwiOiJyaXN0aXJpYW50b2FkaUBnbWFpbC5jb20iLCJlbWFpbF92ZXJpZmllZCI6ZmFsc2UsImZpcmViYXNlIjp7ImlkZW50aXRpZXMiOnsiZW1haWwiOlsicmlzdGlyaWFudG9hZGlAZ21haWwuY29tIl19LCJzaWduX2luX3Byb3ZpZGVyIjoicGFzc3dvcmQifX0.cXRlxdyDlotHbWETa-mmZlwgtTo8ayXlsm9qdDiDhTfr8PslhPrMWjpbukv72rGs17STOu2Virvsj_01fXFD0lz8WgbjeHXT8YZ-gavESD6LMDQ47A_l_8EdRRCVp1-R9Q1QW4z8XSNsUNEVFWtMF9kdh3wNHqyWFj2pcWAAJOib8cuJx1xDuwra89Cip6LJaVLSToyzXx4lIZvjrG8K0Rq2RdK1MV9BesmiEg8Kjf8kB5WGRk29EOFrFS1yzeAJFdAYWMY3RvnTlwELyh54ovgYV1d_7lOolmnzGeJC6Ju295Rj_6s_kMCF8wbPogoMoe6hUqr1yZBoYLlYuuKKOw

{
    "namaPria":"AS Laksana",
    "namaWanita":"Jihan Maulani",
    "latitude":"0-01-021-0121",
    "longitude": "0-01-021-1223",
    "dresscode": "gray",
    "waktuAcara": "10020303010"
}

###

POST http://localhost:5000/acara/-MX-z-kzwafxyFrasQcl/delete
Content-Type: application/json
id-token: eyJhbGciOiJSUzI1NiIsImtpZCI6IjhkOGM3OTdlMDQ5YWFkZWViOWM5M2RiZGU3ZDAwMzJmNjk3NjYwYmQiLCJ0eXAiOiJKV1QifQ.eyJuYW1lIjoiYWRpIiwiaXNzIjoiaHR0cHM6Ly9zZWN1cmV0b2tlbi5nb29nbGUuY29tL2FuZ3VsYXItOTYyOTkiLCJhdWQiOiJhbmd1bGFyLTk2Mjk5IiwiYXV0aF90aW1lIjoxNjE3NTI0NzQwLCJ1c2VyX2lkIjoiRTJWN014NXBqMVRhMXFxSXhnUmdSbXZUUmdnMSIsInN1YiI6IkUyVjdNeDVwajFUYTFxcUl4Z1JnUm12VFJnZzEiLCJpYXQiOjE2MTc1MjQ3NDksImV4cCI6MTYxNzUyODM0OSwiZW1haWwiOiJyaXN0aXJpYW50b2FkaUBnbWFpbC5jb20iLCJlbWFpbF92ZXJpZmllZCI6ZmFsc2UsImZpcmViYXNlIjp7ImlkZW50aXRpZXMiOnsiZW1haWwiOlsicmlzdGlyaWFudG9hZGlAZ21haWwuY29tIl19LCJzaWduX2luX3Byb3ZpZGVyIjoicGFzc3dvcmQifX0.cXRlxdyDlotHbWETa-mmZlwgtTo8ayXlsm9qdDiDhTfr8PslhPrMWjpbukv72rGs17STOu2Virvsj_01fXFD0lz8WgbjeHXT8YZ-gavESD6LMDQ47A_l_8EdRRCVp1-R9Q1QW4z8XSNsUNEVFWtMF9kdh3wNHqyWFj2pcWAAJOib8cuJx1xDuwra89Cip6LJaVLSToyzXx4lIZvjrG8K0Rq2RdK1MV9BesmiEg8Kjf8kB5WGRk29EOFrFS1yzeAJFdAYWMY3RvnTlwELyh54ovgYV1d_7lOolmnzGeJC6Ju295Rj_6s_kMCF8wbPogoMoe6hUqr1yZBoYLlYuuKKOw

###

POST http://localhost:5000/acara/-MX-z-kzwafxyFrasQcl/invitees/baru
Content-Type: application/json
id-token: eyJhbGciOiJSUzI1NiIsImtpZCI6IjhkOGM3OTdlMDQ5YWFkZWViOWM5M2RiZGU3ZDAwMzJmNjk3NjYwYmQiLCJ0eXAiOiJKV1QifQ.eyJuYW1lIjoiYWRpIiwiaXNzIjoiaHR0cHM6Ly9zZWN1cmV0b2tlbi5nb29nbGUuY29tL2FuZ3VsYXItOTYyOTkiLCJhdWQiOiJhbmd1bGFyLTk2Mjk5IiwiYXV0aF90aW1lIjoxNjE3NTI0NzQwLCJ1c2VyX2lkIjoiRTJWN014NXBqMVRhMXFxSXhnUmdSbXZUUmdnMSIsInN1YiI6IkUyVjdNeDVwajFUYTFxcUl4Z1JnUm12VFJnZzEiLCJpYXQiOjE2MTc1MjQ3NDksImV4cCI6MTYxNzUyODM0OSwiZW1haWwiOiJyaXN0aXJpYW50b2FkaUBnbWFpbC5jb20iLCJlbWFpbF92ZXJpZmllZCI6ZmFsc2UsImZpcmViYXNlIjp7ImlkZW50aXRpZXMiOnsiZW1haWwiOlsicmlzdGlyaWFudG9hZGlAZ21haWwuY29tIl19LCJzaWduX2luX3Byb3ZpZGVyIjoicGFzc3dvcmQifX0.cXRlxdyDlotHbWETa-mmZlwgtTo8ayXlsm9qdDiDhTfr8PslhPrMWjpbukv72rGs17STOu2Virvsj_01fXFD0lz8WgbjeHXT8YZ-gavESD6LMDQ47A_l_8EdRRCVp1-R9Q1QW4z8XSNsUNEVFWtMF9kdh3wNHqyWFj2pcWAAJOib8cuJx1xDuwra89Cip6LJaVLSToyzXx4lIZvjrG8K0Rq2RdK1MV9BesmiEg8Kjf8kB5WGRk29EOFrFS1yzeAJFdAYWMY3RvnTlwELyh54ovgYV1d_7lOolmnzGeJC6Ju295Rj_6s_kMCF8wbPogoMoe6hUqr1yZBoYLlYuuKKOw

{
    "invitees":[
        {
            "namaLengkap": "wilham Reyssan",
            "email":"wilhamr.reyssan@gmail.com"
        },
                {
            "namaLengkap": "Farhan Yakub Bawazier",
            "email":"farhan.bawazir16@gmail.com"
        }
    ]
}

###

GET http://localhost:5000/acara/-MX-z-kzwafxyFrasQcl/invitees
Content-Type: application/json
id-token: eyJhbGciOiJSUzI1NiIsImtpZCI6IjhkOGM3OTdlMDQ5YWFkZWViOWM5M2RiZGU3ZDAwMzJmNjk3NjYwYmQiLCJ0eXAiOiJKV1QifQ.eyJuYW1lIjoiYWRpIiwiaXNzIjoiaHR0cHM6Ly9zZWN1cmV0b2tlbi5nb29nbGUuY29tL2FuZ3VsYXItOTYyOTkiLCJhdWQiOiJhbmd1bGFyLTk2Mjk5IiwiYXV0aF90aW1lIjoxNjE3NTI0NzQwLCJ1c2VyX2lkIjoiRTJWN014NXBqMVRhMXFxSXhnUmdSbXZUUmdnMSIsInN1YiI6IkUyVjdNeDVwajFUYTFxcUl4Z1JnUm12VFJnZzEiLCJpYXQiOjE2MTc1MjQ3NDksImV4cCI6MTYxNzUyODM0OSwiZW1haWwiOiJyaXN0aXJpYW50b2FkaUBnbWFpbC5jb20iLCJlbWFpbF92ZXJpZmllZCI6ZmFsc2UsImZpcmViYXNlIjp7ImlkZW50aXRpZXMiOnsiZW1haWwiOlsicmlzdGlyaWFudG9hZGlAZ21haWwuY29tIl19LCJzaWduX2luX3Byb3ZpZGVyIjoicGFzc3dvcmQifX0.cXRlxdyDlotHbWETa-mmZlwgtTo8ayXlsm9qdDiDhTfr8PslhPrMWjpbukv72rGs17STOu2Virvsj_01fXFD0lz8WgbjeHXT8YZ-gavESD6LMDQ47A_l_8EdRRCVp1-R9Q1QW4z8XSNsUNEVFWtMF9kdh3wNHqyWFj2pcWAAJOib8cuJx1xDuwra89Cip6LJaVLSToyzXx4lIZvjrG8K0Rq2RdK1MV9BesmiEg8Kjf8kB5WGRk29EOFrFS1yzeAJFdAYWMY3RvnTlwELyh54ovgYV1d_7lOolmnzGeJC6Ju295Rj_6s_kMCF8wbPogoMoe6hUqr1yZBoYLlYuuKKOw

###

POST http://localhost:5000/acara/-MX-z-kzwafxyFrasQcl/invitees/bmKtMhMkwl19_VS/edit
Content-Type: application/json
id-token: eyJhbGciOiJSUzI1NiIsImtpZCI6IjhkOGM3OTdlMDQ5YWFkZWViOWM5M2RiZGU3ZDAwMzJmNjk3NjYwYmQiLCJ0eXAiOiJKV1QifQ.eyJuYW1lIjoiYWRpIiwiaXNzIjoiaHR0cHM6Ly9zZWN1cmV0b2tlbi5nb29nbGUuY29tL2FuZ3VsYXItOTYyOTkiLCJhdWQiOiJhbmd1bGFyLTk2Mjk5IiwiYXV0aF90aW1lIjoxNjE3NTI0NzQwLCJ1c2VyX2lkIjoiRTJWN014NXBqMVRhMXFxSXhnUmdSbXZUUmdnMSIsInN1YiI6IkUyVjdNeDVwajFUYTFxcUl4Z1JnUm12VFJnZzEiLCJpYXQiOjE2MTc1MjQ3NDksImV4cCI6MTYxNzUyODM0OSwiZW1haWwiOiJyaXN0aXJpYW50b2FkaUBnbWFpbC5jb20iLCJlbWFpbF92ZXJpZmllZCI6ZmFsc2UsImZpcmViYXNlIjp7ImlkZW50aXRpZXMiOnsiZW1haWwiOlsicmlzdGlyaWFudG9hZGlAZ21haWwuY29tIl19LCJzaWduX2luX3Byb3ZpZGVyIjoicGFzc3dvcmQifX0.cXRlxdyDlotHbWETa-mmZlwgtTo8ayXlsm9qdDiDhTfr8PslhPrMWjpbukv72rGs17STOu2Virvsj_01fXFD0lz8WgbjeHXT8YZ-gavESD6LMDQ47A_l_8EdRRCVp1-R9Q1QW4z8XSNsUNEVFWtMF9kdh3wNHqyWFj2pcWAAJOib8cuJx1xDuwra89Cip6LJaVLSToyzXx4lIZvjrG8K0Rq2RdK1MV9BesmiEg8Kjf8kB5WGRk29EOFrFS1yzeAJFdAYWMY3RvnTlwELyh54ovgYV1d_7lOolmnzGeJC6Ju295Rj_6s_kMCF8wbPogoMoe6hUqr1yZBoYLlYuuKKOw
{

    "namaLengkap": "Itas Windriarti P",
    "email":"itawp@gmail.com"
}

###

POST http://localhost:5000/acara/-MX-z-kzwafxyFrasQcl/invitees/-MXKbmL4eqUcCF6PlnV_/hapus
Content-Type: application/json
id-token: eyJhbGciOiJSUzI1NiIsImtpZCI6IjhkOGM3OTdlMDQ5YWFkZWViOWM5M2RiZGU3ZDAwMzJmNjk3NjYwYmQiLCJ0eXAiOiJKV1QifQ.eyJuYW1lIjoiYWRpIiwiaXNzIjoiaHR0cHM6Ly9zZWN1cmV0b2tlbi5nb29nbGUuY29tL2FuZ3VsYXItOTYyOTkiLCJhdWQiOiJhbmd1bGFyLTk2Mjk5IiwiYXV0aF90aW1lIjoxNjE3NTI0NzQwLCJ1c2VyX2lkIjoiRTJWN014NXBqMVRhMXFxSXhnUmdSbXZUUmdnMSIsInN1YiI6IkUyVjdNeDVwajFUYTFxcUl4Z1JnUm12VFJnZzEiLCJpYXQiOjE2MTc1MjQ3NDksImV4cCI6MTYxNzUyODM0OSwiZW1haWwiOiJyaXN0aXJpYW50b2FkaUBnbWFpbC5jb20iLCJlbWFpbF92ZXJpZmllZCI6ZmFsc2UsImZpcmViYXNlIjp7ImlkZW50aXRpZXMiOnsiZW1haWwiOlsicmlzdGlyaWFudG9hZGlAZ21haWwuY29tIl19LCJzaWduX2luX3Byb3ZpZGVyIjoicGFzc3dvcmQifX0.cXRlxdyDlotHbWETa-mmZlwgtTo8ayXlsm9qdDiDhTfr8PslhPrMWjpbukv72rGs17STOu2Virvsj_01fXFD0lz8WgbjeHXT8YZ-gavESD6LMDQ47A_l_8EdRRCVp1-R9Q1QW4z8XSNsUNEVFWtMF9kdh3wNHqyWFj2pcWAAJOib8cuJx1xDuwra89Cip6LJaVLSToyzXx4lIZvjrG8K0Rq2RdK1MV9BesmiEg8Kjf8kB5WGRk29EOFrFS1yzeAJFdAYWMY3RvnTlwELyh54ovgYV1d_7lOolmnzGeJC6Ju295Rj_6s_kMCF8wbPogoMoe6hUqr1yZBoYLlYuuKKOw
###

POST http://localhost:5000/acara/-MX-z-kzwafxyFrasQcl/invitees/kirim-undangan
Content-Type: application/json
id-token: eyJhbGciOiJSUzI1NiIsImtpZCI6IjhkOGM3OTdlMDQ5YWFkZWViOWM5M2RiZGU3ZDAwMzJmNjk3NjYwYmQiLCJ0eXAiOiJKV1QifQ.eyJuYW1lIjoiYWRpIiwiaXNzIjoiaHR0cHM6Ly9zZWN1cmV0b2tlbi5nb29nbGUuY29tL2FuZ3VsYXItOTYyOTkiLCJhdWQiOiJhbmd1bGFyLTk2Mjk5IiwiYXV0aF90aW1lIjoxNjE3NTI4NTQxLCJ1c2VyX2lkIjoiRTJWN014NXBqMVRhMXFxSXhnUmdSbXZUUmdnMSIsInN1YiI6IkUyVjdNeDVwajFUYTFxcUl4Z1JnUm12VFJnZzEiLCJpYXQiOjE2MTc1Mjg1NTAsImV4cCI6MTYxNzUzMjE1MCwiZW1haWwiOiJyaXN0aXJpYW50b2FkaUBnbWFpbC5jb20iLCJlbWFpbF92ZXJpZmllZCI6ZmFsc2UsImZpcmViYXNlIjp7ImlkZW50aXRpZXMiOnsiZW1haWwiOlsicmlzdGlyaWFudG9hZGlAZ21haWwuY29tIl19LCJzaWduX2luX3Byb3ZpZGVyIjoicGFzc3dvcmQifX0.FjawbADgxGH3Km2ngJq_7npX3msi2_8ZwdPtHSfo_xzMIxNbNf5M3IezCxgzBQUFn7NrYW5-gA6QfgEPXzyU2_tgaag1UUWj2NytTHqykFErxkR4iaIjN5kOK7uNSFba-wBaojsAPf9HR73TODZMPnD6UbB079-g5CcvrofQUvv9vBaRU1fr__0XYYnhsLB5Bo6Sv7TZlTxIjnqXuQFpvk8wV2OHTaxscO7rIxibgHgtLeQNSxRGX7Sj2qGJBnjl_3m9UiFBfYK15eCkTdhW6E9WtOc8huyG9sLWdFAhduoGqeK9mSHpuULCSmkQJ8e3gWqq26jvu9TpYuFccYLL_w

###

GET http://localhost:5000/acara/-MX-z-kzwafxyFrasQcl/invitees/-MXKbmKtMhMkwlj19_VS/undangan

###

GET http://localhost:5000/dashboard
id-token: eyJhbGciOiJSUzI1NiIsImtpZCI6IjhkOGM3OTdlMDQ5YWFkZWViOWM5M2RiZGU3ZDAwMzJmNjk3NjYwYmQiLCJ0eXAiOiJKV1QifQ.eyJuYW1lIjoiYWRpIiwiaXNzIjoiaHR0cHM6Ly9zZWN1cmV0b2tlbi5nb29nbGUuY29tL2FuZ3VsYXItOTYyOTkiLCJhdWQiOiJhbmd1bGFyLTk2Mjk5IiwiYXV0aF90aW1lIjoxNjE3NTI0NzQwLCJ1c2VyX2lkIjoiRTJWN014NXBqMVRhMXFxSXhnUmdSbXZUUmdnMSIsInN1YiI6IkUyVjdNeDVwajFUYTFxcUl4Z1JnUm12VFJnZzEiLCJpYXQiOjE2MTc1MjQ3NDksImV4cCI6MTYxNzUyODM0OSwiZW1haWwiOiJyaXN0aXJpYW50b2FkaUBnbWFpbC5jb20iLCJlbWFpbF92ZXJpZmllZCI6ZmFsc2UsImZpcmViYXNlIjp7ImlkZW50aXRpZXMiOnsiZW1haWwiOlsicmlzdGlyaWFudG9hZGlAZ21haWwuY29tIl19LCJzaWduX2luX3Byb3ZpZGVyIjoicGFzc3dvcmQifX0.cXRlxdyDlotHbWETa-mmZlwgtTo8ayXlsm9qdDiDhTfr8PslhPrMWjpbukv72rGs17STOu2Virvsj_01fXFD0lz8WgbjeHXT8YZ-gavESD6LMDQ47A_l_8EdRRCVp1-R9Q1QW4z8XSNsUNEVFWtMF9kdh3wNHqyWFj2pcWAAJOib8cuJx1xDuwra89Cip6LJaVLSToyzXx4lIZvjrG8K0Rq2RdK1MV9BesmiEg8Kjf8kB5WGRk29EOFrFS1yzeAJFdAYWMY3RvnTlwELyh54ovgYV1d_7lOolmnzGeJC6Ju295Rj_6s_kMCF8wbPogoMoe6hUqr1yZBoYLlYuuKKOw
