GET http://localhost:5000/

###

POST http://localhost:5000/acara/baru
Content-Type: application/json

{
    "namaPria":"Farhan Yakub Bawazier",
    "namaWanita":"Ida",
    "latitude":"0-01-021-0121",
    "longitude": "0-01-021-1223",
    "dresscode": "gray",
    "waktuAcara": "10020303010"
}

###

POST http://localhost:5000/acara/-MX-ypFdNBOA95Jr2ETo/invitee/baru
Content-Type: application/json

{
    "invitees":[
        {
            "namaLengkap": "Hanim Pranata",
            "email":"hanimpranata@gmail.com"
        },
                {
            "namaLengkap": "Ita Windriarti P",
            "email":"itawindriartip@gmail.com"
        }
    ]
}

###

POST http://localhost:5000/register
Content-Type: application/json

{
    "email":"farhanyakub@gmail.com",
    "password":"12345678"
}

###

POST http://localhost:5000/login
Content-Type: application/json

{
    "email":"ristiriantoadi@gmail.com",
    "password":"12345678"
}

###

GET http://localhost:5000/dashboard
id-token: eyJhbGciOiJSUzI1NiIsImtpZCI6IjhkOGM3OTdlMDQ5YWFkZWViOWM5M2RiZGU3ZDAwMzJmNjk3NjYwYmQiLCJ0eXAiOiJKV1QifQ.eyJuYW1lIjoiYWRpIiwiaXNzIjoiaHR0cHM6Ly9zZWN1cmV0b2tlbi5nb29nbGUuY29tL2FuZ3VsYXItOTYyOTkiLCJhdWQiOiJhbmd1bGFyLTk2Mjk5IiwiYXV0aF90aW1lIjoxNjE3MzU5MjcwLCJ1c2VyX2lkIjoiRTJWN014NXBqMVRhMXFxSXhnUmdSbXZUUmdnMSIsInN1YiI6IkUyVjdNeDVwajFUYTFxcUl4Z1JnUm12VFJnZzEiLCJpYXQiOjE2MTczNTkyNzIsImV4cCI6MTYxNzM2Mjg3MiwiZW1haWwiOiJyaXN0aXJpYW50b2FkaUBnbWFpbC5jb20iLCJlbWFpbF92ZXJpZmllZCI6ZmFsc2UsImZpcmViYXNlIjp7ImlkZW50aXRpZXMiOnsiZW1haWwiOlsicmlzdGlyaWFudG9hZGlAZ21haWwuY29tIl19LCJzaWduX2luX3Byb3ZpZGVyIjoicGFzc3dvcmQifX0.KNjNqvR5kZEs8G2NAd8YzLaQ1KQqIYM5xMaoguG9uTIolUE083_KeL1NRnMeq7cPsY7j-VYqAsWUeQ1aNuVoM68GIC097BJbu69jJlVP1v2TN1Z2xER9poBNTkninXT9rMx5eiwNkks7oGPWuvk-VrXJJFk_w20Y455X4QymVLb16spu8vjEf2MRTa4Z3zgAN_7aasIfwg8G8avpb4xlsfWqahEqTxmiArbqOZ29j2r3z3NUGMjCpgtKbUEsU7ohKNJ1I3RQ5AYxDzQUZmRNLevbehag25OTBnuMCFsmpREiBJOyd2FSSEzCn-OvjOOUsWV0f95nqQLLiUgfjoEyjw